from __future__ import annotations

# qwen3.5-livetranslate-flash-realtime
# 29 语言支持「文本 + 语音」输出
QWEN_LIVE_SPEECH: list[tuple[str, str]] = [
    ("中文", "zh"),
    ("英语 · English", "en"),
    ("阿拉伯语 · العربية", "ar"),
    ("德语 · Deutsch", "de"),
    ("法语 · Français", "fr"),
    ("西班牙语 · Español", "es"),
    ("葡萄牙语 · Português", "pt"),
    ("印度尼西亚语 · Bahasa Indonesia", "id"),
    ("意大利语 · Italiano", "it"),
    ("韩语 · 한국어", "ko"),
    ("俄语 · Русский", "ru"),
    ("泰语 · ไทย", "th"),
    ("越南语 · Tiếng Việt", "vi"),
    ("日语 · 日本語", "ja"),
    ("土耳其语 · Türkçe", "tr"),
    ("印地语 · हिन्दी", "hi"),
    ("马来语 · Bahasa Melayu", "ms"),
    ("荷兰语 · Nederlands", "nl"),
    ("乌尔都语 · اردو", "ur"),
    ("挪威语 · Norsk", "nb"),
    ("瑞典语 · Svenska", "sv"),
    ("丹麦语 · Dansk", "da"),
    ("希伯来语 · עברית", "he"),
    ("芬兰语 · Suomi", "fi"),
    ("波兰语 · Polski", "pl"),
    ("冰岛语 · Íslenska", "is"),
    ("捷克语 · Čeština", "cs"),
    ("菲律宾语 · Filipino", "fil"),
    ("波斯语 · فارسی", "fa"),
]

# 31 语言仅支持文本输出
QWEN_LIVE_TEXT_ONLY: list[tuple[str, str]] = [
    ("粤语 · 粵語", "yue"),
    ("希腊语 · Ελληνικά", "el"),
    ("南非荷兰语 · Afrikaans", "af"),
    ("阿斯图里亚斯语 · Asturianu", "ast"),
    ("白俄罗斯语 · Беларуская", "be"),
    ("保加利亚语 · Български", "bg"),
    ("孟加拉语 · বাংলা", "bn"),
    ("波斯尼亚语 · Bosanski", "bs"),
    ("加泰罗尼亚语 · Català", "ca"),
    ("宿务语 · Cebuano", "ceb"),
    ("爱沙尼亚语 · Eesti", "et"),
    ("加利西亚语 · Galego", "gl"),
    ("古吉拉特语 · ગુજરાતી", "gu"),
    ("克罗地亚语 · Hrvatski", "hr"),
    ("匈牙利语 · Magyar", "hu"),
    ("爪哇语 · Basa Jawa", "jv"),
    ("哈萨克语 · Қазақ", "kk"),
    ("卡纳达语 · ಕನ್ನಡ", "kn"),
    ("柯尔克孜语 · Кыргыз", "ky"),
    ("拉脱维亚语 · Latviešu", "lv"),
    ("马其顿语 · Македонски", "mk"),
    ("马拉雅拉姆语 · മലയാളം", "ml"),
    ("马拉地语 · मराठी", "mr"),
    ("旁遮普语 · ਪੰਜਾਬੀ", "pa"),
    ("罗马尼亚语 · Română", "ro"),
    ("斯洛伐克语 · Slovenčina", "sk"),
    ("斯洛文尼亚语 · Slovenščina", "sl"),
    ("斯瓦希里语 · Swahili", "sw"),
    ("塔吉克语 · Тоҷикӣ", "tg"),
    ("阿塞拜疆语 · Azərbaycan", "az"),
    ("乌克兰语 · Українська", "uk"),
]

# 60 语言全集（输入/字幕目标可用，同传目标仅 SPEECH 29 个）
QWEN_LIVE_ALL: list[tuple[str, str]] = QWEN_LIVE_SPEECH + QWEN_LIVE_TEXT_ONLY

QWEN_LANG_NAME_BY_CODE: dict[str, str] = {
    "zh": "Chinese", "en": "English", "ar": "Arabic", "de": "German",
    "fr": "French", "es": "Spanish", "pt": "Portuguese", "id": "Indonesian",
    "it": "Italian", "ko": "Korean", "ru": "Russian", "th": "Thai",
    "vi": "Vietnamese", "ja": "Japanese", "tr": "Turkish", "hi": "Hindi",
    "ms": "Malay", "nl": "Dutch", "ur": "Urdu", "nb": "Norwegian",
    "sv": "Swedish", "da": "Danish", "he": "Hebrew", "fi": "Finnish",
    "pl": "Polish", "is": "Icelandic", "cs": "Czech", "fil": "Filipino",
    "fa": "Persian",
    "yue": "Cantonese", "el": "Greek", "af": "Afrikaans", "ast": "Asturian",
    "be": "Belarusian", "bg": "Bulgarian", "bn": "Bengali", "bs": "Bosnian",
    "ca": "Catalan", "ceb": "Cebuano", "et": "Estonian", "gl": "Galician",
    "gu": "Gujarati", "hr": "Croatian", "hu": "Hungarian", "jv": "Javanese",
    "kk": "Kazakh", "kn": "Kannada", "ky": "Kyrgyz", "lv": "Latvian",
    "mk": "Macedonian", "ml": "Malayalam", "mr": "Marathi", "pa": "Punjabi",
    "ro": "Romanian", "sk": "Slovak", "sl": "Slovenian", "sw": "Swahili",
    "tg": "Tajik", "az": "Azerbaijani", "uk": "Ukrainian",
}
